language: objective-c
xcode_project: linphone.xcodeproj
xcode_scheme: linphone
xcode_sdk: iphonesimulator8.1

branches:
  only:
    - master

env:
    global:
        - VERSION="8.1"
        - secure: "JPPcWdmNIJiR3YcIwe0LRYce6qDdsiagO+eKKAp7eVk/wD9UHbz96Ms2FFkXxPhRJB1PA6Pf8FpAzIL2YRiJL9jRtKHSvtdF1cSto+57XyBkCsw7PkMVUIxp7fg6Wiwn3H3tucF8jisIkv/Pn7R+9EqePkZSqqu3+ig5AX9ApQ4="

before_install:
    - brew update
    - brew install doxygen nasm gettext yasm optipng imagemagick coreutils intltool
    - brew outdated cmake || brew upgrade cmake
    - brew link gettext --force
    - brew tap Gui13/linphone
    - brew install antlr3.2
    - wget --no-check-certificate https://raw.github.com/yuvi/gas-preprocessor/master/gas-preprocessor.pl
    - chmod +x gas-preprocessor.pl
    - sudo mv gas-preprocessor.pl /usr/local/bin
    - sudo ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
    - sudo ln -s /usr/bin/strings /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/strings
    - git submodule update --init --recursive

install:
    - ./prepare.py all
    - make -s 1>/dev/null
    - mkdir -p Screens
    - export KIF_SCREENSHOTS=`pwd`/Screens

after_script:
    - ./Tools/imgur_upload.sh
