language: objective-c
env:
  global:
  - KIF_SCREENSHOTS=$PWD/Screens
  - secure: lDv+Wq4AwTOYxAza+n0gU51gT35tcOo97QlEWR2v+4vqakR3FROLQJQNHCTcYs2uTQV4B1F44d+J1RKnvb4MtzXq+NR/80yZv3N+Guw1RyOvBMD8jNmMq6TUuaJ01qpkX/JAMvbyvDm6L52s1RK09SUUcJTQEMkK68X7JEwfkxQuSJVS1ULlZiSw5IQHIDys+7U6uoyhllUqaBDYtcXEDKt1cDvJQpmBKgy6gQ1dLF7734Nryb0Gyi2m6zMUoLT0CRc0E/A3K07klhc35YU0OF1P4VbYU6+k/pDuCTuSq+/tAHDeu3d4dMbpFLcPwZ8OeEAkCLdZdh+vEcUmmgVpg19Pd57QdW5B0Ib9garOQ3hB8+lmW3/EpiZtA/lnuRn0t3mcu3Tr0ThhuD8JLZjB+yrPW8jvXync29SOQPDkP6FGhmapgU8f5jivww+DEIcdC12ZuYznAQanupqv4td5MwebFXZl1qyZECP6rH66kHHPvcGy4QIy1EFMwfgo8tms57u2nDOuocU2xsSTD5zBtZZ0wvzjiejN3tXg4uaso1x3Qi8VA5lbFC5zIDz2/DqOFymQfPe17+qZbX3mCm0Qi9LmCRk3c79XL8yUlfDRXNrg48aWhtED65kD0Ri1V3018g4KFwUPdR7IlvGOoeGVOIackSnbC6V4KEULkVNnKys=
  - secure: DkrV4zq8u5YkNDcgGsVpyQx4Yko6o/05Aj6mKO+jSoMslar3r48idd033nd0VYfueI4qPxA43MHnBEyk0+Jmfz147zEkJXVCu7qIsNn24HXhLszvcPTj/8nA+1eI+SYtSkwxj/cgn2TyWIWF2DDGW0dNv4jMCk4bDgpNz2hB2Z14/38YtfCf+dyuCAs9BhqxSkoeOHZ+2g/ZrvclvH39QSR/FCpASP5QTJfhuZ8nMyX8x+y+Q2kVljuG37BqR8MwdcXHBl1ufEAw9nOcWJ/dPtcFJotpEiQPWmsUK7BMPSrqH5KY1Zwh4Eh00wKA8DEIZ7k4HRxdfbUKjt+FmiYfToU5JvVReTwu54EywF6b48VvVId5KYBX9IH61uu/Jzy5BzYKkCvpv0DAkv56UEwCb/cuwZWeXWgguf7fEa+3XNvnNYLhfh/84AlFVNvq7bIV0RF/aAwKmQhv1Seml6pPp9mRXm/iPQ+EN6j0rfJ8pvvUFTl+jITGgniHy5xojLnTog2Y56+cHf+1oLupxUfuGWE8tIEsW8mcdbeDkCuqjBDh3MtFp55Wtcl6As+uNloNG7w+xEY5kEGinxthnlivv7Jt/t2V9Mqq7oF7xJy8awsioN4ajNRs2bWt+AOWNOHs+0orKcJSi+AEzLr28GMKy7+0FbvYIF0/eA915mJLc/Q=
before_install:
- brew update 1>/dev/null
- brew install doxygen nasm yasm optipng imagemagick coreutils intltool ninja antlr
- brew upgrade cmake
- wget --no-check-certificate https://raw.github.com/yuvi/gas-preprocessor/master/gas-preprocessor.pl
- chmod +x gas-preprocessor.pl
- sudo mv gas-preprocessor.pl /usr/local/bin
- sudo ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
- sudo ln -s /usr/bin/strings /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/strings
- git submodule update --init --recursive
- bundle install
install:
- "./prepare.py -d all -G Ninja"
- "./Tools/travis_script.sh"
script:
- xctool -project linphone.xcodeproj -scheme linphone -sdk iphoneos -configuration
  Debug build 1>/dev/null
after_success:
- "./Tools/release.sh"
notifications:
  flowdock:
    secure: XulX1WBdwcW09KFJOfPgRNzb08jGavzPPfpj9slg5Xk9Ib83cduJo04wVanbA92xVBsgLPNPvuu441LFqNRn3w6xbVDA75JyTmT1ih+W8VaaBZLfovrAbmpBEpXk3VUqn7UID+Hl/rkfYO+9fw+qPzJnomRMZ04ldc8hUfHH3ImfO3B8dMt1IMSaoy88A7f4/Vm4EGXWDDY35ZJxO560w5Rr9QgiALllpHdgxHDScJK73RceDi75gUfvNIZqW7c/AQI7dJ6QbQ15Esw2i/x5eHIGMYCheXPiazW6/3GONrz5cmcZ7ecEDPLMVvzKS38DN5iAFwZ5kFixS/h30WhcVsT6ZWPcDWHyJGNWGRqpwJn/IROCb+0f6Y2BtZ4ReDEq5nHPviZvN4eTi9uvWs8jE+8wh2DpJ9VfAu8UADouzxfK7W/A5YgcQA+6Q98anlAICfwCsobcS72MWa4MoUFscKlxe8byqL+ZZWxoEGq79s6OIMuVtTqpNEaLCDflHUAv9q+hDXXyTHMGhrCplQ7b8yfv7JAmmareqnz6V+FsGj3gd6sbLK+W9TQ8y8wnJAX6ZZvfIIPbqzKHc12I5Y0jJmkTLfrrMfE5kQ8uK9GquAvMsjySNYO6+0ljcLi09+yo40gi+tcRXTYtjhjqr8O5Qj0N0I+39xF/TPiaMXKqBmk=
